### ISSUE TITLE
Download button in whitepaper download section is hidden on mobile

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#13]
You have to scroll it to find the buttons on the right but its not obvious

**Comment by angusfretwell** [comment]
<img width="393" alt="screen shot 2017-07-10 at 10 26 28 pm" src="https://user-images.githubusercontent.com/3889818/28017998-da608a46-65be-11e7-82ae-a42c255154dd.png">

**Comment by gz-c** [comment]
![img_1204](https://user-images.githubusercontent.com/26845312/28018145-b36fc2f4-65ae-11e7-939e-448b81bd10f0.PNG)
