### ISSUE TITLE
Skycoin.net, Downloads Page Wallet page improvements, remove text

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin.net#160]
Delete "For simple use, download the Desktop wallet. For advanced use, or slow connections, the CLI wallet provides a UI that runs directly in your browser."

---

Too much white space between "download" and "torrent". Fix whitespace. Remove file size.

---

Put .zip, .tar.gz into its own column after "Download"

**Comment by nutmix** [comment]
@gz-c this item appears to be solved and live?
