### ISSUE TITLE
Skycoin OTC Purchase -- Clarification

### ISSUE THREAD

**Issue by josepharubin** [skycoin/skycoin.net#175]
Hello, I'm trying to purchase Skycoin on the website (OTC), and want to get this question answered: Can I send my BTC straight from an exchange to the bitcoin address?

I'm sure that I'm not the only individual with this question, so if you could, please update the Skycoin OTC page to include whether you can or cannot send BTC straight from an exchange. 

Thank you!

**Comment by gz-c** [comment]
You can send directly from an exchange, but it is not recommended to do this.  See this thread: https://www.reddit.com/r/SkycoinProject/comments/7jymgn/skycoin_otc_begins_12152017/draausj/

**Comment by gz-c** [comment]
You can send directly from an exchange, but it is not recommended to do this.  See this thread: https://www.reddit.com/r/SkycoinProject/comments/7jymgn/skycoin_otc_begins_12152017/draausj/

> NEVER send from an exchange. If something goes wrong, your coins are lost. And if you need to prove you own the sending address, you can't.
