### ISSUE TITLE
Add Huffington Post logo to main page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#188]
And link it to https://www.huffingtonpost.com/entry/the-top-5-crypto-projects-to-watch-in-2018_us_5a4c6a77e4b06cd2bd03e359

**Comment by nutmix** [comment]
This is now complete for the current site. Needs to be added to the new version (develop branch)

**Comment by colinswilliams** [comment]
Closing, it's part of the new design, and we're moving to Hugo instead of using the develop branch on this repo
