### ISSUE TITLE
Update forbes logo link

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#189]
Change the link to https://www.forbes.com/sites/julesschroeder/2018/01/09/millennials-heres-how-cryptocurrency-could-transform-your-future/2/#7f061b5e1dc7

**Comment by nutmix** [comment]
This is now complete for current site. Needs to be done for the New version of the site (develop branch)

**Comment by colinswilliams** [comment]
Closing, it's part of the new design, and we're moving to Hugo instead of using the develop branch on this repo
