### ISSUE TITLE
Update blog.skycoin.net links to /blog

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#192]

**Comment by gz-c** [comment]
This was done by changing the travis build scripts for the blog repo to sync to the s3 bucket+key www.skycoin.net/blog

A redirect was set on the blog.skycoin.net bucket, to redirect all to www.skycoin.net/blog

**Comment by gz-c** [comment]
@nutmix this is still open, the link to Blog in the header points to blog.skycoin.net, not www.skycoin.net/blog

**Comment by nutmix** [comment]
FYI, the [pull request submitted yesterday](https://github.com/skycoin/skycoin.net/pull/231) updates the blog links on develop. Not sure why the pull request didn't show in the above history.
