### ISSUE TITLE
Downloads page: change "Installer" to "Binary (with logs)"

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#202]
Right now it says "Standalone" to refer to the electron app and "Installer" to refer to the binary release that can be run from the command line.

The "Installer" version doesn't install anything. The "Standalone" could also be described as "Installer".

The "Installer" version can be double-clicked on Windows and a cmd window will open with logs displayed, which is helpful for troubleshooting users. The GUI opens as a webpage in the browser.  On OS X and Linux, the user would need to run the binary from their terminal.

Rename "Installer" to "Binary (with logs)" (I can't think of anything better and apparently "CLI" was too intimidating of a name).

Should we add a description to the page, the difference between "Standalone" and "Binary"/"CLI"?

**Comment by nutmix** [comment]
I recommend changing it to this (for windows at least)

"installer (recommended)"
"portable (command line, advanced users)"

I would also recommend the following for both:
1. for windows distribution, remove the .md files as:
   1.  they cannot be opened on windows by default (no app)
   1.  they only have linux & OSX information.
1. create a readme.txt with windows instructions for installing and running each (e.g. you have to unblock the network access in the popup (see attached screen shot))

![image](https://user-images.githubusercontent.com/5080942/35267585-10f6cd6a-0027-11e8-9b5f-24987d40c81b.png)

The standalone IS an installer.  So it would appear that

  standalone => installer (with nice UI), task bar short cut and no cmd windows.
  installer => portable (with cmd "log" window, local web server with browser based UI)


You could also add "which version should I choose section":

installer gives you an easy to use seamless wallet application.
portable gives you maximum control for developers and power users.  It gives you a view of the blockchain transactions as they happen.  The wallet runs in your browser against a local server.

For the portable (cmd) version, you definitely need instructions how to run it.  E.g. if you close the browser, and the cmd is still running in the background, and you try to re-run the cmd to open it again, nothing happens. There needs to be a readme.txt or instructions on the web page (or both) which says that you just need to open a new browser window and hit "http://127.0.0.1:6420/#/wallets"

**Comment by gz-c** [comment]
Suggested changes to the release themselves should be posted to https://github.com/skycoin/skycoin

The naming changes for installer/portable are good, you can proceed with that for the downloads page

**Comment by nutmix** [comment]
The best solution might be to have the installation instructions on the website as a link next to the download link, with instructions like to "allow access" as in screen shot above.  The instructions for the portable version could be in the readme, but there needs to be a windows version of this also (txt file).
