### ISSUE TITLE
robots.txt for staging2.skycoin.net

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#206]
Do the same for this, but apply to staging2.skycoin.net as well https://github.com/skycoin/skycoin.net/pull/204

Just need to make this same PR to the develop branch

**Comment by nutmix** [comment]
Looking at the .travis.yml files in both the develop and master branch, both files have both devlop and master branches defined in them.   I suspect either one of these two is being used, or that each has a redundant section which will lead to confusion.   I will investigate to see which is the case and propose a cleanup.  (more logical might be to have the new site in its own repo  on its own master branch (e.g. as a fork of current repo).  That way there is no confusion, and it can  track its own tickets.

**Comment by gz-c** [comment]
@nutmix you can submit a PR for that to fix the travis yml
