### ISSUE TITLE
Markets page copy changes

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#211]
1) There is a spelling error. Next to Cryptopia it currently reads "expereincing" instead of "experiencing". 

2) For C2CX it's missing the SKY/USDT book, which doesn't have huge volumes, but is OK for smaller amounts (less than 100 SKY). For this book I suggest you note that C2CX only supports the new USDT ERC20 token, i.e. via the Ethereum blockchain. (The old bitcoin blockchain based tether using the Omni protocol is being phased out.) The link for this is https://www.c2cx.com/in/trade_usdt_sky.

3) C2CX no longer has any CNY books. It does however have a SKY/DRG book which is the one the skycoin markets page links to. You can note that 100 CNY = 1 DRG.

**Comment by colinswilliams** [comment]
Changes on staging

**Comment by gz-c** [comment]
What about staging2? New site does not have markets page?

**Comment by colinswilliams** [comment]
I've left staging2 a bit untouched at the moment as a lot of the changes on
my forked develop branch do some refactoring, and restructuring of
components on the existing site (while still working with existing ones, as
not every page is being redesigned yet) but obviously with the number of
changes that have taken place this past week or so on the master branch,
those should also make their way over to develop, so they don't get missed.

Good catch, I'll get them over there. PR on develop should be coming in a
couple days, just want to have something solid enough to really show off a
more or less finished page.

-- 
Colin Williams

**Comment by gz-c** [comment]
Leaving this open for staging2

**Comment by colinswilliams** [comment]
Added to develop branch
