### ISSUE TITLE
Put the skywire mailing list link back on the front page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#223]
https://www.skycoin.net/mailing-list/

**Comment by nutmix** [comment]
Its on the current version of the site.   Is this request  for the develop branch?
What is the difference between staging and staging2?

**Comment by colinswilliams** [comment]
Sorting this out now

**Comment by colinswilliams** [comment]
Removed staging2 label, as this content isn't present in the new design. If there is need for it to be present, I think that becomes a different story/requirement. Merging final revision to staging now, and then will cut a new tag.
