### ISSUE TITLE
Brandon web change 1 - change huffington post.

### ISSUE THREAD

**Issue by nutmix** [skycoin/skycoin.net#264]
1. remove huffington post logo on home page
1. Add 

    "Top 5 Crypto Projects to Watch in 2018" Karl Kangur - CEO of Result Compass
 
centered above the logos in the same container, and have it link to https://www.huffingtonpost.com/entry/the-top-5-crypto-projects-to-watch-in-2018_us_5a4c6a77e4b06cd2bd03e359

Chose a font which looks good. Center the remaining logos

**Comment by colinswilliams** [comment]
Merged, on staging now
