### ISSUE TITLE
Fix Skycoin Buttons On Home Page

### ISSUE THREAD

**Issue by moonmoney** [skycoin/skycoin.net#285]
<img width="497" alt="screen shot 2018-03-01 at 6 35 13 am" src="https://user-images.githubusercontent.com/36955725/36843413-e2c03522-1d1c-11e8-862f-ace78f3e7fc0.png">

change request:

- On mobile and on desktop, when the width of the window is sized down, the buttons move down to the bottom of the Map image with no space between them and the bottom of that image.

- Change it so that there is equidistant space below and above the buttons when resized.

**Comment by colinswilliams** [comment]
Working with the existing code for changes like this aren't quite as easy to pull off while keeping in line with the existing patterns. I did adjust the margins to make sure the buttons don't overlap with the content below it, and tried to adjust the top to clear the image, but it'd take more effort to 100% lock it in with clearing the image.

Code pushed, tagged and merged to prod
