### ISSUE TITLE
Add link to chinese whitepaper on whitepapers page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#292]
https://downloads.skycoin.net/whitepapers/%E5%8A%A0%E5%AF%86%E8%B4%A7%E5%B8%81%E7%BD%91%E7%BB%9C%E5%88%86%E5%B8%83%E5%BC%8F%E5%85%B1%E8%AF%86%E7%AE%97%E6%B3%95%E7%99%BD%E7%9A%AE%E4%B9%A6.pdf

Title:

加密货币网络分布式共识算法白皮书

**Comment by colinswilliams** [comment]
What placement would you like this in? Apparently the download list isn't localized, so all locales will have this link (and the others)

**Comment by gz-c** [comment]
@colinswilliams put it in the whitepaper list, its fine if its shown for all languages

**Comment by colinswilliams** [comment]
Added, resolved issues with tagging as well, all recent changes should be on prod now
