### ISSUE TITLE
Post-release fixes needed

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#3]
- [x] /index.html 404s [page loads but react shows 404 page]
- [x] /downloads.html white screen
- [x] /faqs.html white screen [FAQ page removed; redirect to /]
- [x] /whitepapers.html goes to old site
- [x] /infographics.html goes to old site
- [x] Link to Explorer in header
- [ ] Show build version on downloads page
- [ ] Create new page to show infographics from http://skycoin.net/infographics.html [mirror: https://imgur.com/a/IqEZI]
- [x] "Read the whitepaper" should say "whitepapers"
- [x] "Read the whitepaper" link should go to http://skycoin.net/downloads#whitepapers

**Comment by angusfretwell** [comment]
Thanks for capturing this 👍

**Comment by angusfretwell** [comment]
Redirects and content changes are done. Raised #5 & #6 for build version and infographics page.
