### ISSUE TITLE
Update downloads to new wallet version 0.22.0

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#313]
Download links are listed here:

https://github.com/skycoin/skycoin/releases/tag/v0.22.0

This release includes PGP signatures, which should be added to the downloads page, as mentioned in #180

**Comment by gz-c** [comment]
This done for the master branch, the future site will need to have the latest wallet version and the signature files.

**Comment by AlexSugak** [comment]
Updated to latest version on new site
