### ISSUE TITLE
Add chinese language whitepaper

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#368]
URL: https://downloads.skycoin.net/whitepapers/Skycoin-Whitepaper-V3.1%E4%B8%AD%E6%96%87%E7%89%88.pdf

This is the chinese translation of the whitepaper.  Add it alongside all occurrences of the english language whitepaper.  The title is "Skycoin Whitepaper V3.1中文版"

**Comment by AlexSugak** [comment]
fixed in skycoin/skycoin.net#369
