### ISSUE TITLE
Add logos to homepage

### ISSUE THREAD

**Issue by angusfretwell** [skycoin/skycoin.net#40]
- Forbes
- Alphabit Fund
- Blockchain News

**Comment by jessesunfei** [comment]
[https://www.forbes.com/sites/laurashin/2017/07/12/crypto-boom-15-new-hedge-funds-want-in-on-84000-returns/#474bd847416a](url)
[http://www.the-blockchain.com/2017/08/01/skycoin-launches-vision-new-internet/](url)
[http://www.alphabit.fund/](url)
![blockchiannews logo](https://user-images.githubusercontent.com/15919421/29203383-c5c215e4-7e70-11e7-8f8a-ff02ca4802db.jpg)
![forbes logo](https://user-images.githubusercontent.com/15919421/29203384-c5e03678-7e70-11e7-9b7c-543da5400ef1.jpg)

**Comment by jessesunfei** [comment]
not been able to upload the logo of Alphabet.fund due to its format. but you can get it on their website easily  http://www.alphabit.fund/
