### ISSUE TITLE
Separations on the downloads page should be more evident

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin.net#473]
Some users have reported, in Telegram, problems with the wallet and it has turned out to be that they have not downloaded the correct version. Mainly, users have been downloading the portable version instead of the installer, which has given them problems. The problem seems to be unusual, because there have not been many reports, but it exists.

Due to this, and taking into account that the list of options for downloading the wallet is more complex than other lists on the website, it would be good to make the separation between operating systems more evident and make it more obvious that users should normally download the installer and not the portable version.

**Comment by nutmix** [comment]
I would suggest highlighting the installer for the users OS (from browser string).  E.g. make it bold with a outline to show it is the recommended installer.

**Comment by kzviagina** [comment]
@nutmix made recommended download bold, changed grey color in table. Please check on your monitor.

**Comment by nutmix** [comment]
@kzviagina thanks, is it on one of the servers to view?

**Comment by kzviagina** [comment]
@nutmix sorry, forgot to mention this - https://staging.skycoin.net/downloads/

**Comment by haroonskycoin** [comment]
This was addressed last year and implemented
