### ISSUE TITLE
Visual defect on explorer.skycoin.net logo.

### ISSUE THREAD

**Issue by caariiboouu** [skycoin/skycoin.net#520]
Seems to depend on the size of the svg element when rendering.
![ezgif-5-594626dfdbce](https://user-images.githubusercontent.com/7329254/46548150-d8eda200-c893-11e8-9131-c59e90f35fc5.gif)

Appears to fix when exporting again from Illustrator with three decimal places. [https://cuthriell.com/logo-adjusted%20copy.svg](https://cuthriell.com/logo-adjusted%20copy.svg)

**Comment by haroonskycoin** [comment]
@gz-c is https://explorer.skycoin.net serving a cached version of the logo? https://github.com/skycoin/skycoin-explorer/blob/develop/src/assets/img/logo.svg and the [svg file](data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53%0D%0AMy5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNTkgNDAiPjxkZWZzPjxzdHlsZT4uY2xzLTF7%0D%0AZmlsbDojMDI3M2ZmO30uY2xzLTJ7ZmlsbDojMjUyNzI5O308L3N0eWxlPjwvZGVmcz48dGl0bGU+%0D%0ATG9nbyAmYW1wO2FtcDsgSWNvbl9SZXNpemVkLVJlZm9udDwvdGl0bGU+PHBhdGggY2xhc3M9ImNs%0D%0Acy0xIiBkPSJNMjAuNTIzLjc1MWEuNjc4LjY3OCwwLDAsMS0uMTEuMzM4UTE0LjgyNSwxMy4xNTEs%0D%0AOS4yMzYsMjUuMjExTDYuNTYzLDMwLjk3OWMtLjA0Mi4wOS0uMDkyLjE3OC0uMTI3LjI3MS0uMDU0%0D%0ALjE0NC0uMTQ1LjE0OS0uMjY0LjA4NS0uMDc3LS4wNDEtLjE1Ny0uMDc3LS4yMzMtLjExOEExMC4z%0D%0ALDEwLjMsMCwwLDEsLjMxMiwyMy4zLDEwLjUyNiwxMC41MjYsMCwwLDEsOC40MjEsMTEuNTI0YTku%0D%0ANjg1LDkuNjg1LDAsMCwxLDIuMDM3LS4yNWMuMywwLC4zLS4wMTMuMzEyLS4zMThBMTAuNTU2LDEw%0D%0ALjU1NiwwLDAsMSwxOS4yLjkyNCw2LjE1NSw2LjE1NSwwLDAsMSwyMC41MjMuNzUxWiIvPjxwYXRo%0D%0AIGNsYXNzPSJjbHMtMSIgZD0iTTI1LjU3MywxLjYwOSwyNC4zMzksNC4yNzNxLTYuMzksMTMuNzkx%0D%0ALTEyLjc4MSwyNy41ODNjLS4yNTUuNTQ4LS4yNTQuNTQ5LS44NzYuNTQxYTEwLjQ0NywxMC40NDcs%0D%0AMCwwLDEtMy4zMzctLjU4M2MtLjA4Mi0uMDI5LS4xNjQtLjA1OS0uMjQ1LS4wOTJhLjI3Ni4yNzYs%0D%0AMCwwLDEtLjA1Ny0uMDQ5LDEuMTI5LDEuMTI5LDAsMCwxLC4xNDgtLjM3OHE3LTE1LjExNCwxNC4w%0D%0AMDctMzAuMjI5QTEuMTc4LDEuMTc4LDAsMCwwLDIxLjI1OS45My4zMTQuMzE0LDAsMCwxLDIxLjYy%0D%0ANC43YTEwLjg3NywxMC44NzcsMCwwLDEsMy4xODYuNTkyQTQuMjUxLDQuMjUxLDAsMCwxLDI1LjU3%0D%0AMywxLjYwOVoiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMi40NDUsMzIuMzZhLjc0OC43NDgs%0D%0AMCwwLDEsLjEyMy0uMzQzcTYuODQzLTE0Ljc3MSwxMy42OTEtMjkuNTRjLjIzNC0uNTA2LjEzNC0u%0D%0ANS42MzgtLjE5MmExMC43NDMsMTAuNzQzLDAsMCwxLDIuNDY1LDIuMS40MzMuNDMzLDAsMCwxLC4w%0D%0ANzMuNTU3cS0xLjk0NSw0LjE2Ni0zLjg3MSw4LjM0MUwxNi44ODgsMzIuMDFhMS42MTMsMS42MTMs%0D%0AMCwwLDAtLjA3Ny4xNy4yOS4yOSwwLDAsMS0uMzM1LjIyMmMtLjMxOCwwLS40MjQsMC0uNjM2LDBx%0D%0ALTEuNTksMC0zLjE4LDBDMTIuNTksMzIuNCwxMi41MTIsMzIuNDIxLDEyLjQ0NSwzMi4zNloiLz48%0D%0AcGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0zMC40LDUuODZhMTAuNDc3LDEwLjQ3NywwLDAsMSwxLjI0%0D%0ALDMuMDczLDEwLjM0OSwxMC4zNDksMCwwLDEsLjI1NCwyLDEuMzYyLDEuMzYyLDAsMCwxLS4xMzYu%0D%0ANjQ2UTI3LjQsMjAuOTcyLDIzLjA0NywzMC4zNjhjLS4yNzcuNi0uNTU2LDEuMi0uODMxLDEuOC0u%0D%0AMDU5LjEyNy0uMTA1LjIzNy0uMjg2LjIzNi0xLjI0Ny0uMDA3LTIuNDkzLDAtMy43MzEsMC0uMDE0%0D%0ALS4wMzEtLjAyLS4wNDEtLjAyNC0uMDUzcy0uMDEzLS4wMjUtLjAxLS4wMzRjLjA0LS4xLjA3Ny0u%0D%0AMjEuMTI0LS4zMTFaIi8+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMjMuODc1LDMyLjM4OEEuNzQx%0D%0ALjc0MSwwLDAsMSwyNCwzMmw5LjM2Ni0yMC4yMTcuMDQ5LS4xYy4xMzctLjI4My4xMzgtLjI5LjQ1%0D%0AMy0uMjI5YTEwLjExNiwxMC4xMTYsMCwwLDEsMS44MzEuNTJjLjI5LjExNC41NjkuMjU0Ljg1OC4z%0D%0ANjkuMTc1LjA3LjE3OC4xNi4xLjMxNS0uMzg4LjgyMy0uNzY2LDEuNjUtMS4xNDksMi40NzVRMzEu%0D%0ANiwyMy41ODIsMjcuNjg4LDMyLjAyOWEuNTM1LjUzNSwwLDAsMS0uNTc4LjM3OGMtMS0uMDIzLTIt%0D%0ALjAwOC0yLjk5NC0uMDA5QzI0LjA0MiwzMi40LDIzLjk2OCwzMi4zOTIsMjMuODc1LDMyLjM4OFoi%0D%0ALz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0zOC4zMzQsMTMuNDY0YTEwLjg1NiwxMC44NTYsMCww%0D%0ALDEsMi4xMywyLjE2OWMuMTM2LjE4LjA3My4zMTcsMCwuNDc4cS0uOSwxLjkzMy0xLjc5MywzLjg2%0D%0AOC0yLjc3NSw1Ljk4OC01LjU0LDExLjk4MWEuNjIzLjYyMywwLDAsMS0uNjQ0LjQyNnEtMS40NCww%0D%0ALTIuODgxLDBDMjkuNjM3LDMyLjExNSwzNy45LDE0LjE4OCwzOC4zMzQsMTMuNDY0WiIvPjxwYXRo%0D%0AIGNsYXNzPSJjbHMtMSIgZD0iTTM1LjU2NCwzMS43LDQxLjc5LDE4LjI2NEExMC40NDEsMTAuNDQx%0D%0ALDAsMCwxLDM1LjU2NCwzMS43WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTU0LjgzOSwyNi44%0D%0ANTZhNi43MTEsNi43MTEsMCwwLDAsNC44MSwyLjI0NSwyLjY4NiwyLjY4NiwwLDAsMCwyLjk3NC0y%0D%0ALjU2NmMwLTIuNjI0LTMuNzktMi45NDQtNi41My00LjU0OGE1LjE0OSw1LjE0OSwwLDAsMS0yLjg4%0D%0ANy00LjYzNWMwLTMuNjQ0LDMuMzUzLTUuNzQzLDYuNzM1LTUuNzQzYTkuNDQ1LDkuNDQ1LDAsMCwx%0D%0ALDUuOTE4LDEuOTI0bC0yLjA0MSwyLjkxNWE1LjQ2LDUuNDYsMCwwLDAtMy41MjctMS4zNDFjLTEu%0D%0ANDg3LDAtMy4xNDkuNjQxLTMuMTQ5LDIuMjE2LDAsMy4yOTQsOS40MTcsMi4yNzQsOS40MTcsOS4x%0D%0ANTQsMCwzLjYxNS0zLjIzNiw2LjEyMi02LjkxLDYuMTIyYTEwLjg4OSwxMC44ODksMCwwLDEtNy4z%0D%0ANzYtMy4wNjFaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNzYuNywyNC41MjRsNy43ODQsNy43%0D%0AODRoLTUuMWwtNS45NzctNi4xMjN2Ni4xMjNINjkuNjJ2LTIwLjdoMy43ODlWMjIuNzQ1bDQuODY5%0D%0ALTQuNTc3aDUuMzM1WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTg3Ljc4MSwzOS4zbDMuOTA3%0D%0ALTguNDI1TDg1LjM2MiwxOC4xNjhIODkuNTNsNC4xNCw4LjQ4NCwzLjgxOS04LjQ4NGgzLjk5NEw5%0D%0AMS43NDYsMzkuM1oiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xMTYuNjQzLDI5LjQyMWE3LjUs%0D%0ANy41LDAsMCwxLTYuNDE0LDMuMTc4LDcuMzY1LDcuMzY1LDAsMSwxLC4wMy0xNC43MjIsNy41NDIs%0D%0ANy41NDIsMCwwLDEsNS45NDcsMi44MjhsLTIuNjgyLDIuMzYxYTQuMSw0LjEsMCwwLDAtMy4yNjUt%0D%0AMS42OTEsMy43OTEsMy43OTEsMCwwLDAtMy44MiwzLjg3NywzLjczNywzLjczNywwLDAsMCwzLjkw%0D%0ANywzLjg0OSw0LjE0Myw0LjE0MywwLDAsMCwzLjM4Mi0xLjg2NloiLz48cGF0aCBjbGFzcz0iY2xz%0D%0ALTIiIGQ9Ik0xMjUuOTE0LDE3Ljg3N2E3LjM2Myw3LjM2MywwLDEsMS03LjUyMiw3LjM3NUE3LjM2%0D%0AMiw3LjM2MiwwLDAsMSwxMjUuOTE0LDE3Ljg3N1ptMCwxMS4yMjRhMy42OTQsMy42OTQsMCwwLDAs%0D%0AMy43MzEtMy44NDksMy43MzQsMy43MzQsMCwxLDAtNy40NjMsMEEzLjY5NCwzLjY5NCwwLDAsMCwx%0D%0AMjUuOTE0LDI5LjFaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNMTM4LjUzNywxMC43MzRhMi40%0D%0AMjEsMi40MjEsMCwxLDEtMi40NzgsMi40MkEyLjQyNywyLjQyNywwLDAsMSwxMzguNTM3LDEwLjcz%0D%0ANFptMS44OTUsMjEuNTc0aC0zLjc5VjE4LjE2OGgzLjc5WiIvPjxwYXRoIGNsYXNzPSJjbHMtMiIg%0D%0AZD0iTTE0NC44MDUsMzIuMzA4VjE4LjE2OGgzLjY0NHYxLjEzN2E2LjIzOCw2LjIzOCwwLDAsMSwz%0D%0ALjk5NC0xLjQyOCw2LjM3MSw2LjM3MSwwLDAsMSw0LjksMi4yNzQsNy4xMzQsNy4xMzQsMCwwLDEs%0D%0AMS40NTcsNC45NTZ2Ny4yaC0zLjc5VjI0LjgxNWEzLjQxOCwzLjQxOCwwLDAsMC0uODQ1LTIuNjUz%0D%0ALDIuOTg0LDIuOTg0LDAsMCwwLTIuMTI4LS43ODcsNC41MTEsNC41MTEsMCwwLDAtMy40NCwxLjc0%0D%0AOXY5LjE4NFoiLz48L3N2Zz4=) show the updated version

**Comment by gz-c** [comment]
try staging.explorer.skycoin.net

**Comment by haroonskycoin** [comment]
@caariiboouu thanks for the heads up.  This has been fixed via https://github.com/skycoin/skycoin-explorer/pull/301
