### ISSUE TITLE
Problems with the menus

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin.net#573]
The main menu looks like this when the browser window is 640px wide or more:

![menu1](https://user-images.githubusercontent.com/34079003/51336086-1e586880-1a5a-11e9-83b4-5cf053809e35.png)

Additionally, the layout of the footer menu has problems in some resolutions:

![logo](https://user-images.githubusercontent.com/34079003/51336171-43e57200-1a5a-11e9-9689-d1aa6aef4200.png)
![menu2](https://user-images.githubusercontent.com/34079003/51336184-4ba51680-1a5a-11e9-9560-31f63761782a.png)

**Comment by berli96** [comment]
fixed on #692

**Comment by haroonskycoin** [comment]
@Senyoret1 thanks for the heads up, this has been fixed
