### ISSUE TITLE
Pageload is 5MB; likely hurting search rank.

### ISSUE THREAD

**Issue by caariiboouu** [skycoin/skycoin.net#673]
Consider compressing these image files. I've attached optimized versions with ~60% savings, without much noticeable quality loss.
wallet2.4f8b8679.png
miner5.d00231e0.png
miner1.6081e0e4.png
miner2.987cb6ff.png
wallet3.ecfcebe6.png
wallet1.811d3117.png
[optimized.zip](https://github.com/skycoin/skycoin.net/files/3173705/optimized.zip)

**Comment by haroonskycoin** [comment]
@caariiboouu thanks for the heads up, it just got fixed https://github.com/skycoin/skycoin.net/pull/682
