### ISSUE TITLE
Wallet Build Should Have Date

### ISSUE THREAD

**Issue by SkyAudit** [skycoin/skycoin.net#79]
Wallet Build is missing the date. Date should be associate with the wallet build

https://www.skycoin.net/downloads/

**Comment by gz-c** [comment]
Need more specific detail

**Comment by SkyAudit** [comment]
Like usually the file versions have a specific time stamp as to when the file was updated. I think we should include that in our download page to provide more information to the consumer

**Comment by SkyAudit** [comment]
This will tell people if they have the latest build or not.

**Comment by meam364** [comment]
@SkyAudit where i can get current build date?

**Comment by gz-c** [comment]
I don't think there is a build date available

**Comment by SkyAudit** [comment]
Maybe for the future release.
