### ISSUE TITLE
Upload BBS Binaries

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skycoin.net#80]
Have a **BBS** section in **Downloads** page under **Wallet** with the following content:

### BBS
Skycoin BBS is a next generation decentralized social network built with the Skycoin Ecosystem.

_**[Downloads Here]**_
* https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_linux_amd64.zip
* https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_osx_amd64.zip
* https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_windows_amd64.zip

^ Note that these are all 64bit binaries; Linux, mac and windows.

**Comment by evanlinjin** [comment]
https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_linux_amd64.zip
https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_osx_amd64.zip
https://downloads.skycoin.net/bbs/skycoin_bbs_3.1_windows_amd64.zip

**Comment by evanlinjin** [comment]
Only after this is put up, can we publish this blog post: https://github.com/skycoin/blog/pull/104

**Comment by meam364** [comment]
#82
