### ISSUE TITLE
Skycoin.net edits

### ISSUE THREAD

**Issue by SkyAudit** [skycoin/skycoin.net#81]
Here is the new copy. Can we update the content on the website?

Speed:
Skycoin transactions take as little as 4 seconds. With no bottlenecks or fees, Skycoin is faster than other cryptocurrencies and competitive with credit cards and Apple Pay. It’s perfect for Point of Sale (POS) and IOT applications.

Privacy:
Transactions are anonymous and untraceable. Skycoin uses G. Maxwell’s CoinJoin protocol to mix transactions from multiple wallets, giving you total privacy online.

Security:
: Skycoin is secure. It’s built from the ground up in Golang, using time-tested cryptographic standards. That means your transactions can’t be tampered with. Skycoin protects you from threats like 51% attack, reversal, duplication, and malleability.

Ecosystem:
The Skycoin universe is growing. We’re expanding the ecosystem to include multifunctional tools and real-world web apps that improve your experience. A meshnet, distributed exchange, messaging, social media, and VPN are just the beginning.

Sustainability:
Skycoin is eco-friendly. It doesn’t waste electricity by mining. Powered by the first new consensus algorithm since PeerCoin, Skycoin avoids costly proof-of-work (POW) and proof-of-stake (POS) processes.

Utility:
Skycoin is more than a cryptocurrency. It’s a token that powers Skywire, the new alternative internet. With Skycoin, you get all the benefits of a digital currency plus a ticket into the future of decentralized networking.

**Comment by SkyAudit** [comment]
Instead of:
Revolutionary new consensus algorithm

Satoshi originally intended the Bitcoin network to be decentralized, over hundreds of thousands of computers. Today, the Bitcoin network is completely controlled by three mining pools. Bitcoin is no longer decentralized. Skycoin's consensus algorithm is designed to achieve true decentralization of blockchain consensus.


Change to:

Obelisk: A Revolutionary Consensus Algorithm

Skycoin’s new algorithm goes beyond PoW and PoS to decentralize blockchain consensus. Unlike Bitcoin, which is monopolized by three mining pools, Skycoin offers a truly democratic digital currency. We're bringing Satoshi’s original vision to users everywhere. Read more about Obelisk and the Skycoin revolution at:

**Comment by gz-c** [comment]
Don't mention apple pay

**Comment by gz-c** [comment]
The consensus algorithm section is already updated on staging.skycoin.net

**Comment by gz-c** [comment]
"Skycoin uses G. Maxwell’s CoinJoin protocol to mix transactions from multiple wallets, giving you total privacy online."

**Comment by gz-c** [comment]
Removing this section
