### ISSUE TITLE
Change "Revolutionary new consensus algorithm" section

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin.net#85]
The section should look similar to this:
<img width="983" alt="screen shot 2017-09-08 at 7 33 32 pm" src="https://user-images.githubusercontent.com/26845312/30209890-c0b8d692-94cc-11e7-9e64-ac87f1132e62.png">

Here is the new graphic to use on the right side:

![photo_2017-09-08_19-21-35](https://user-images.githubusercontent.com/26845312/30209901-cdd0c79a-94cc-11e7-8fcd-987ac649663e.jpg)

Move the blue "Whitepapers" button from the "What is Skycoin?" section to this section.

Change title to "Obelisk: The Skycoin Consensus Algorithm"

Make the title <a href="https://blog.skycoin.net/statement/obelisk-the-skycoin-consensus-algorithm/">Obelisk: The Skycoin Consensus Algorithm</a>

**Comment by meam364** [comment]
#87
